export const dashboard = `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>LitGraph · 使用统计</title><style>
:root{--ink:#242137;--muted:#736b85;--line:#dcd5e7;--accent:#6945cf;--surface:#fff;--canvas:#f7f6fb}*{box-sizing:border-box}body{font:15px/1.6 "Segoe UI",system-ui,sans-serif;color:var(--ink);background:var(--canvas);max-width:1160px;margin:40px auto;padding:0 24px}h1{font-size:28px;letter-spacing:-.5px;margin:0}h2{font-size:19px;margin:32px 0 8px}.eyebrow{color:var(--accent);font-weight:600;letter-spacing:.08em;font-size:12px}p{color:var(--muted)}form{display:flex;gap:12px;align-items:end;flex-wrap:wrap;padding:20px 0;border-bottom:1px solid var(--line)}label{display:grid;gap:6px;font-size:13px}input,button{font:inherit;border:1px solid var(--line);border-radius:8px;padding:10px 14px;min-height:44px}input{width:300px;max-width:100%;background:var(--surface)}button{background:var(--accent);color:white;cursor:pointer}button:disabled{opacity:.6;cursor:wait}:focus-visible{outline:2px solid var(--accent);outline-offset:3px}.cards{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin:20px 0}.card{background:var(--surface);border:1px solid var(--line);border-radius:10px;padding:18px}.card strong{display:block;font-size:28px;font-weight:600;line-height:1.3;margin:8px 0;font-variant-numeric:tabular-nums}.card span{font-size:13px}.card small{display:block;color:var(--muted);font-size:12px}.table-scroll{overflow:auto;border:1px solid var(--line);border-radius:10px;background:var(--surface)}table{width:100%;border-collapse:collapse;white-space:nowrap;font-variant-numeric:tabular-nums}td,th{padding:12px 16px;border-bottom:1px solid var(--line);text-align:right;font-size:13px}th{font-weight:600;background:var(--canvas)}td:first-child,th:first-child{text-align:left}tr:last-child td{border-bottom:0}#error{color:#a33333}#updated{font-size:13px}.note{font-size:13px}#report[hidden]{display:none}@media(max-width:850px){.cards{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:480px){body{margin:24px auto;padding:0 16px}.card{padding:12px}.card strong{font-size:24px}form label{width:100%}input{width:100%}}
</style></head><body><header><div class="eyebrow">LITGRAPH / 1.2.0</div><h1>从首次打开，到持续研究</h1><p>安装、活跃使用与留存统计 · 每日按北京时间划分</p></header>
<form id="login"><label for="token">查看密钥<input id="token" type="password" required autocomplete="off" placeholder="输入查看密钥"></label><button id="load">查看统计</button></form><p id="error" role="alert"></p>
<main id="report" hidden><p id="updated" role="status"></p><div id="summary" class="cards"></div>
<h2>每日使用</h2><p class="note">日活统计当天执行过核心操作的安装数；打开软件不等于实际使用。同一安装多次操作只计一个日活。</p><div class="table-scroll"><table aria-label="每日使用统计"><thead><tr><th>日期</th><th>新增安装</th><th>活跃使用 DAU</th><th>有活动的安装</th><th>打开次数</th><th>使用次数</th></tr></thead><tbody id="rows"></tbody></table></div>
<h2>用户留存</h2><p class="note">按首次启动日期分组，第 1、7、30 天发生核心操作才计入留存；不是“期间内回来过”。当天观察值仍在累计，尚未到观察日期显示待观察。</p><div class="table-scroll"><table aria-label="次日七日三十日留存"><thead><tr><th>首次启动日期</th><th>新增安装</th><th>次日留存</th><th>7 日留存</th><th>30 日留存</th></tr></thead><tbody id="retention-rows"></tbody></table></div>
<p class="note">口径：新增安装以首次收到启动或使用记录为准，无法证明安装程序完成。按随机安装标识去重，同一人多设备分别计数；重装且丢失标识会新增计数。使用次数表示操作发起，不代表检索、下载或回答成功。离线补传可能修正历史数字，未上报活动无法统计。仅使用既有匿名事件，不收集论文、问题、账号或密钥。</p></main>
<script>
const pct=value=>value==null?'—':(value*100).toFixed(1)+'%';
function row(parent,values){const tr=document.createElement('tr');for(const value of values){const td=document.createElement('td');td.textContent=value;tr.append(td);}parent.append(tr);}
document.querySelector('#login').onsubmit=async e=>{
 e.preventDefault();const button=document.querySelector('#load'),error=document.querySelector('#error');button.disabled=true;button.textContent='读取中…';error.textContent='';document.querySelector('#report').hidden=true;
 try{const response=await fetch('/stats',{headers:{Authorization:'Bearer '+document.querySelector('#token').value.trim()}});if(!response.ok)throw Error(response.status===401?'查看密钥不正确，请重新输入。':'暂时无法读取统计，请稍后重试。');const data=await response.json(),s=data.summary;
 const cards=[['累计安装',data.totalInstalls,'自首次记录以来'],['每日活跃使用',s.dau,s.today+' · DAU'],['7 日活跃使用',s.wau,s.weekStart+' 至 '+s.today+' · 去重'],['30 日活跃使用',s.mau,s.monthStart+' 至 '+s.today+' · 去重'],['30 日新增安装',s.newInstalls30,'最近 30 个日历日（含今天）'],['新增首日激活率',pct(s.activationRate30),s.activated30+'/'+s.newInstalls30+' · 30 日新增中首日有使用'],['今日回访使用',s.returningToday,'首次启动早于今天，今天有使用'],['DAU / MAU',pct(s.dauMauRatio),'今日使用占 30 日活跃比例'],['今日人均操作',s.actionsPerActive==null?'—':s.actionsPerActive.toFixed(1),'今日使用次数 ÷ 今日活跃使用']];
 const summary=document.querySelector('#summary');summary.replaceChildren();for(const [label,value,note]of cards){const card=document.createElement('section');card.className='card';for(const [tag,text]of [['span',label],['strong',value],['small',note]]){const el=document.createElement(tag);el.textContent=text;card.append(el);}summary.append(card);}
 const days=document.querySelector('#rows');days.replaceChildren();for(const d of data.days)row(days,['day','newInstalls','usedInstalls','activeInstalls','launches','uses'].map(k=>d[k]));if(!data.days.length)row(days,['暂无上报记录','—','—','—','—','—']);
 const retention=document.querySelector('#retention-rows');retention.replaceChildren();for(const c of data.retention)row(retention,[c.cohort,c.installs,...[1,7,30].map(n=>{const r=c['day'+n];return r.mature?r.count+'/'+c.installs+' · '+pct(r.rate)+(r.provisional?'（今日累计）':''):'待观察';})]);
 document.querySelector('#updated').textContent='已更新 · '+new Date().toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})+'（北京时间）';document.querySelector('#report').hidden=false;
 }catch(err){error.textContent=err.message;}finally{button.disabled=false;button.textContent='刷新统计';}
};
</script></body></html>`;
