import assert from 'node:assert/strict';
import {browserAccessState} from '../desktop/browser-access.mjs';
const url='https://publisher.example/article';
assert.equal(browserAccessState('<h1>There was a problem providing the content you requested</h1><p>CPE00001</p>',url),'blocked');
assert.equal(browserAccessState('<title>Paper</title><p>CPE00001 mentioned in a paper.</p>',url),'page');
assert.equal(browserAccessState('<title>Just a moment...</title><script>window._cf_chl_opt={}</script>',url),'challenge');
assert.equal(browserAccessState('<div class="cf-turnstile"></div>',url),'interactive');
assert.equal(browserAccessState('<iframe src="https://challenges.cloudflare.com/turnstile"></iframe>',url),'interactive');
assert.equal(browserAccessState('<input type="password">',url),'login');
const articleWithSignIn='<title>Article</title><h1>Research article</h1><dialog hidden><input type="password"></dialog>';
assert.equal(browserAccessState(articleWithSignIn,url,{hasVisiblePassword:false}),'page','An inactive sign-in modal must not stop an accessible article');
assert.equal(browserAccessState(articleWithSignIn,url,{hasVisiblePassword:true}),'login','An actually visible password form must pause automation');
assert.equal(browserAccessState(articleWithSignIn,url,{}),'login','HTML-only callers retain the conservative password fallback');
assert.equal(browserAccessState('<title>Sign in</title>','https://publisher.example/login',{hasVisiblePassword:false}),'login','A sign-in route remains gated before its form renders');
assert.equal(browserAccessState('<form><input name="SAMLRequest" type="hidden"></form>',url,{hasVisiblePassword:false}),'login','SSO handoff remains gated without a password field');
assert.equal(browserAccessState('<title>Just a moment...</title>',url,{hasVisiblePassword:false}),'challenge','Visibility must not bypass a browser challenge');
const articleWithHiddenCaptcha='<title>Article</title><h1>Research article</h1><dialog hidden><input type="password"><div class="g-recaptcha"></div></dialog>';
assert.equal(browserAccessState(articleWithHiddenCaptcha,url,{hasVisiblePassword:false,hasVisibleChallenge:false}),'page','An inactive CAPTCHA in a hidden sign-in modal must not stop the article');
assert.equal(browserAccessState(articleWithHiddenCaptcha,url,{hasVisiblePassword:false,hasVisibleChallenge:true}),'interactive','A visible CAPTCHA must pause automation');
assert.equal(browserAccessState(articleWithHiddenCaptcha,url,{hasVisiblePassword:false}),'interactive','HTML-only CAPTCHA callers retain the conservative widget fallback');
assert.equal(browserAccessState('<title>Verify you are human</title>',url,{hasVisibleChallenge:false}),'interactive','An explicit human-verification title must not depend on widget visibility');
assert.equal(browserAccessState('<title>Just a moment...</title>',url,{hasVisibleChallenge:false}),'challenge','A challenge title remains blocked before its widget renders');
assert.equal(browserAccessState('<title>Loading</title>','https://publisher.example/cdn-cgi/challenge-platform/h/b/orchestrate/chl_page/v1',{hasVisibleChallenge:false}),'challenge','A direct challenge route remains gated');
assert.equal(browserAccessState('<title>Loading</title>','https://challenges.cloudflare.com/turnstile/v0',{hasVisibleChallenge:false}),'challenge','The hosted challenge document remains gated');
assert.equal(browserAccessState('<title>Article</title><div hidden><iframe src="https://challenges.cloudflare.com/turnstile"></iframe></div>',url,{hasVisibleChallenge:false}),'page','A hidden challenge iframe does not gate the whole article');
assert.equal(browserAccessState('<title>Paper</title><p>We discuss captcha and Cloudflare.</p>',url),'page');
console.log('Browser access classification passed');
