import {_electron as electron} from 'playwright-core';
import assert from 'node:assert/strict';
import {mkdir,mkdtemp,readFile,writeFile,access} from 'node:fs/promises';
import path from 'node:path';
const root=process.cwd();await mkdir('output/desktop',{recursive:true});
const dataRoot=await mkdtemp(path.join(root,'output/desktop/settings-'));
const packaged=Boolean(process.env.LITGRAPH_TEST_EXECUTABLE);
const options={executablePath:process.env.LITGRAPH_TEST_EXECUTABLE||path.join(root,'node_modules/electron/dist/electron.exe'),args:packaged?[]:[root],env:{...process.env,LITGRAPH_TEST_MODE:'1',LITGRAPH_TEST_DATA:dataRoot},timeout:45000};delete options.env.ELECTRON_RUN_AS_NODE;
const retained=['originals/paper.pdf','markdown/paper.md','analysis/paper.json','vectors/paper.json','projects/project.json'];
for(const name of retained){await mkdir(path.dirname(path.join(dataRoot,'data',name)),{recursive:true});await writeFile(path.join(dataRoot,'data',name),'retain fixture '+name);}
let app;
try{
 app=await electron.launch(options);let page=await app.firstWindow();const errors=[];page.on('pageerror',error=>errors.push(error.message));
 await page.locator('#empty-sample-project').click();
 await page.waitForFunction(()=>JSON.parse(localStorage.getItem('litgraph.projects.v1')||'{}')['sample-project']?.data?.nodes?.length===50);
 const graphBefore=await page.evaluate(()=>JSON.parse(localStorage.getItem('litgraph.projects.v1'))['sample-project'].data);
 await page.evaluate(async()=>{
  localStorage.setItem('litgraph.chat.v2.sample-project.project.','[{"role":"user","text":"Keep this conversation"}]');
  localStorage.setItem('litgraph.summary.fixture','Keep this edited analysis');
  localStorage.setItem('litgraph.institutionLibraryUrl','https://library.example.edu');
  localStorage.setItem('litgraph.researchMode','expert');
  localStorage.setItem('litgraph.citationStyle','apa');
  localStorage.setItem('litgraph.language','en');
  await window.litgraphDesktop.saveConfig({endpoint:'https://fixture.invalid/v1',apiKey:'synthetic-not-a-real-key',model:'fixture',verified:true});
  window.litgraphDesktop.saveState({...localStorage});
 });
 await page.reload();await page.locator('#project-selector-label').waitFor();
 await page.locator('[data-panel="workspace-settings"]').click();await page.locator('[data-workspace-action="api"]').click();
 assert.equal(await page.locator('#delete-api-config').innerText(),'Delete configuration');
 await page.locator('#delete-api-config').click();
 await page.waitForFunction(()=>document.querySelector('#api-key').value==='');
 assert.equal(await page.evaluate(()=>window.litgraphDesktop.bootstrap().config),null);
 await assert.rejects(access(path.join(dataRoot,'model-config.encrypted')));
 assert.equal(await page.locator('#api-endpoint').inputValue(),'');
 assert.equal(await page.evaluate(()=>localStorage.getItem('litgraph.institutionLibraryUrl')),'https://library.example.edu','API delete must not clear institution settings');
 await page.screenshot({path:'output/desktop/settings-api-en.png'});
 await page.locator('[data-close-modal="api"]').first().click();
 await page.locator('[data-workspace-action="reset-settings"]').click();
 assert.match(await page.locator('[role="alertdialog"]').innerText(),/No research data is deleted/);
 await page.locator('[data-reset-cancel]').click();
 assert.equal(await page.evaluate(()=>localStorage.getItem('litgraph.researchMode')),'expert');
 await page.evaluate(async()=>{
  await window.litgraphDesktop.saveConfig({endpoint:'https://fixture.invalid/v1',apiKey:'synthetic-reset-key',model:'fixture',verified:true});
  const {browserToken}=await fetch('/__litgraph/bootstrap',{method:'POST'}).then(r=>r.json());
  const response=await fetch('/__litgraph/instructions',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${browserToken}`},body:'{}'});
  if(!response.ok)throw Error('Fixture pairing failed');
 });
 assert.equal(JSON.parse(await readFile(path.join(dataRoot,'agent-guide/pairing.json'),'utf8')).enabled,true);
 await app.evaluate(async({session})=>session.fromPartition('persist:litgraph-institution').cookies.set({url:'https://library.example.edu',name:'fixture',value:'synthetic-session',secure:true}));
 await page.locator('[data-workspace-action="reset-settings"]').click();
 await page.screenshot({path:'output/desktop/settings-reset-en.png'});
 await page.locator('[data-reset-confirm]').click();
 await page.waitForFunction(()=>document.documentElement.lang.startsWith('zh')&&!document.querySelector('[data-reset-confirm]'));
 assert.equal(await page.evaluate(()=>window.litgraphDesktop.bootstrap().config),null);
 assert.equal(await page.evaluate(()=>localStorage.getItem('litgraph.institutionLibraryUrl')),null);
 assert.equal(JSON.parse(await readFile(path.join(dataRoot,'agent-guide/pairing.json'),'utf8')).enabled,false);
 assert.equal(await page.evaluate(()=>localStorage.getItem('litgraph.researchMode')),null);
 assert.equal(await page.evaluate(()=>localStorage.getItem('litgraph.chat.v2.sample-project.project.')),'[{"role":"user","text":"Keep this conversation"}]');
 assert.equal(await page.evaluate(()=>localStorage.getItem('litgraph.summary.fixture')),'Keep this edited analysis');
 assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('litgraph.projects.v1'))['sample-project'].data),graphBefore);
 assert.deepEqual(await app.evaluate(async({session})=>session.fromPartition('persist:litgraph-institution').cookies.get({})),[]);
 for(const name of retained)assert.equal(await readFile(path.join(dataRoot,'data',name),'utf8'),'retain fixture '+name);
 await app.close();app=await electron.launch(options);page=await app.firstWindow();await page.locator('#project-selector-label').waitFor();
 assert.equal(await page.evaluate(()=>window.litgraphDesktop.bootstrap().config),null);
 assert.deepEqual(await app.evaluate(async({session})=>session.fromPartition('persist:litgraph-institution').cookies.get({})),[]);
 assert.equal(await page.evaluate(()=>localStorage.getItem('litgraph.activeProjectId')),'sample-project');
 assert.equal(errors.length,0,errors.join('\n'));
 console.log(JSON.stringify({passed:true,packaged,dataRoot,tested:['API delete and field clearing','institution settings unaffected by API delete','reset cancel','settings-only reset','encrypted institution session cleared','original/MD/analysis/vector/project/chat preservation','restart persistence','English localization']}));
}finally{await app?.close().catch(()=>{});}
