import assert from 'node:assert/strict';
import http from 'node:http';
import {mkdtemp,readFile,rm,mkdir,writeFile,readdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {localService} from './local-service.js';
const root=await mkdtemp(path.join(tmpdir(),'litgraph-persistence-test-'));
const pdf=Buffer.from('%PDF-1.4\nSynthetic storage fixture, not a real paper.\n%%EOF');
const paper={recordId:'verified',title:'Storage fixture',doi:'10.1234/test',authors:['A','B'],year:2024,isOpenAccess:true,pdfUrls:['https://example.org/p.pdf']};
let resolverCalls=0;
const dependencies={scholarly:{search:async()=>({papers:[paper]}),enrich:async p=>({...p,referenceDois:['10.1234/reference']}),resolveOpenAccess:async p=>{resolverCalls++;return p;}},download:async()=>({bytes:pdf,url:'https://example.org/p.pdf'})};
let middleware=localService(root,dependencies);
const server=http.createServer((req,res)=>middleware(req,res,()=>{res.statusCode=404;res.end();}));await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}/__litgraph/`;
async function call(route,data,token){const r=await fetch(base+route,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify(data)});return {status:r.status,data:await r.json()};}
try{
 const token=(await call('bootstrap',{})).data.browserToken;await call('search',{},token);
 assert.equal((await call('acquire',{recordId:'invented'},token)).status,400);
 const acquired=(await call('acquire',{recordId:'verified',projectId:'project',nodeId:'node'},token)).data;
 assert.equal(Buffer.from(acquired.data,'base64').toString(),pdf.toString());assert.ok(acquired.originalRelativePath);
 assert.equal(resolverCalls,0,'An already accessible PDF must not wait for alternative repositories');
 const saved=(await call('document',{projectId:'project',nodeId:'node',markdown:'# Original\n\nEvidence text',fileName:'paper.md'},token)).data;
 assert.equal((await readFile(path.join(root,saved.markdownRelativePath),'utf8')).includes('Evidence'),true);
 dependencies.download=async()=>({bytes:Buffer.from('<html>Sign in required</html>'),url:'https://example.org/login'});
 middleware=localService(root,dependencies);const restrictedToken=(await call('bootstrap',{})).data.browserToken;await call('search',{},restrictedToken);
 const unavailable=(await call('acquire',{recordId:'verified',projectId:'project',nodeId:'unavailable'},restrictedToken)).data;
 assert.equal(unavailable.status,'unavailable');assert.equal(unavailable.data,undefined);assert.equal(unavailable.originalRelativePath,undefined);assert.match(unavailable.error,/instead of a PDF/);
 dependencies.download=async address=>address.endsWith('/p.pdf')?{bytes:Buffer.from('<html><meta name="citation_pdf_url" content="/actual.pdf"></html>'),url:address}:{bytes:pdf,url:address};
 middleware=localService(root,dependencies);const landingToken=(await call('bootstrap',{})).data.browserToken;
 const viaLanding=(await call('acquire',{recordId:'verified',projectId:'project',nodeId:'landing'},landingToken)).data;
 assert.equal(viaLanding.data,pdf.toString('base64'));
 dependencies.download=async()=>{throw Object.assign(Error('Source HTTP 404'),{status:404});};
 middleware=localService(root,dependencies);const missingToken=(await call('bootstrap',{})).data.browserToken;
 const missing=(await call('acquire',{recordId:'verified',projectId:'project',nodeId:'missing'},missingToken)).data;
 assert.equal(missing.attempts[0].code,'not_found');assert.match(missing.error,/link is missing or has moved/);assert.equal(missing.retryable,false);
 const movedRoot=await mkdtemp(path.join(tmpdir(),'litgraph-moved-test-'));
 try{
  const {cp}=await import('node:fs/promises');await cp(path.join(root,'data'),path.join(movedRoot,'data'),{recursive:true});
  middleware=localService(movedRoot,dependencies);const fresh=(await call('bootstrap',{})).data.browserToken;
  const original=(await call('original',{key:saved.key},fresh)).data;assert.equal(Buffer.from(original.data,'base64').toString(),pdf.toString());
  assert.match((await call('document',{key:saved.key},fresh)).data.markdown,/Evidence/);
  const reconciled=(await call('document-state',{projectId:'project',nodeId:'node'},fresh)).data;
  assert.equal(reconciled.key,saved.key);assert.match(reconciled.markdown,/Evidence/);
  // A different page and relocated data root can resume using the persisted search catalogue.
  const reused=(await call('acquire',{recordId:'verified',projectId:'project',nodeId:'node'},fresh)).data;
  assert.equal(reused.data,acquired.data);
  const jobs=[{id:'job',projectId:'project',items:[{nodeId:'node',stage:'paused'}]}];
  assert.equal((await call('discovery-history',{jobs},fresh)).status,200);
  assert.deepEqual(JSON.parse(await readFile(path.join(movedRoot,'data','records','discovery-history.json'),'utf8')),jobs);
  let opened;
  let dataFolder;
  middleware=localService(movedRoot,{...dependencies,openOriginal:async file=>{opened=file;},openDataFolder:async file=>{dataFolder=file;}});
  const nativeToken=(await call('bootstrap',{})).data.browserToken;
  assert.equal((await call('open-native',{key:saved.key},nativeToken)).data.opened,true);
  assert.equal(opened,path.join(movedRoot,saved.originalRelativePath));
  assert.equal((await call('open-native',{key:'../../outside'},nativeToken)).status,400);
  assert.equal((await call('original',{key:'../../outside'},nativeToken)).data,null);
  const folder=(await call('data-folder',{path:'../../ignored'},nativeToken)).data;
  assert.equal(folder.opened,true);assert.equal(dataFolder,path.join(movedRoot,'data'));
  assert.deepEqual((await readdir(dataFolder)).sort(),['analysis','markdown','originals','projects','records','vectors']);
  const legacyKey='a'.repeat(64),legacy=path.join(movedRoot,'projects','local-fulltext-index');await mkdir(legacy,{recursive:true});
  await writeFile(path.join(legacy,legacyKey+'.pdf'),pdf);
  await writeFile(path.join(legacy,legacyKey+'.json'),JSON.stringify({key:legacyKey,originalRelativePath:'projects/local-fulltext-index/'+legacyKey+'.pdf',markdown:'# Retained legacy text',localMarkdownPath:'Z:/old-device/obsolete.md'}));
  const migrated=(await call('document-state',{key:legacyKey},nativeToken)).data;
  assert.equal(migrated.originalRelativePath,`data/originals/${legacyKey}.pdf`);
  assert.match(await readFile(path.join(dataFolder,'markdown',legacyKey+'.md'),'utf8'),/Retained legacy/);
  assert.deepEqual(await readFile(path.join(legacy,legacyKey+'.pdf')),pdf);
  assert.equal((await call('project',{projectId:'project',project:{nodes:[{id:'node',analysisStatus:'done',summary:'Source-backed analysis',claimLabel:'Original finding',analysisWarnings:['Skipped an unsupported link'],embedding:[.1,.2],semanticVectorMethod:'tf-idf'}],semanticLinks:[],citationLinks:[]}},nativeToken)).data.saved,true);
  const analysisFiles=await readdir(path.join(dataFolder,'analysis')),vectorFiles=await readdir(path.join(dataFolder,'vectors'));
  assert.equal(analysisFiles.length,1);assert.equal(vectorFiles.length,1);
  assert.match(await readFile(path.join(dataFolder,'analysis',analysisFiles[0]),'utf8'),/Source-backed analysis/);
  assert.match(await readFile(path.join(dataFolder,'analysis',analysisFiles[0]),'utf8'),/Skipped an unsupported link/);
  assert.deepEqual(JSON.parse(await readFile(path.join(dataFolder,'vectors',vectorFiles[0]),'utf8')).papers[0].embedding,[.1,.2]);
  assert.equal(JSON.parse(await readFile(path.join(dataFolder,'vectors',vectorFiles[0]),'utf8')).papers[0].method,'tf-idf');
 }finally{await rm(movedRoot,{recursive:true,force:true});}
 console.log('Durable full text: verified acquisition, PDF + MD persistence, fresh session, moved project root and traversal rejection passed.');
}finally{await new Promise(r=>server.close(r));await rm(root,{recursive:true,force:true});}
