import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFile} from 'node:fs/promises';
import worker,{validateEvent,recordEvent,installHash} from '../cloudflare/metrics/worker.js';
const sqlite=new DatabaseSync(':memory:');sqlite.exec(await readFile(new URL('../cloudflare/metrics/schema.sql',import.meta.url),'utf8'));
const db={prepare(sql){return {bind(...args){this.args=args;return this;},async first(){return sqlite.prepare(sql).get(...(this.args||[]));},async all(){return {results:sqlite.prepare(sql).all(...(this.args||[]))};},async run(){return sqlite.prepare(sql).run(...(this.args||[]));}};},async batch(statements){sqlite.exec('BEGIN');try{for(const s of statements)await s.run();sqlite.exec('COMMIT');}catch(e){sqlite.exec('ROLLBACK');throw e;}}};
const body={installId:crypto.randomUUID(),eventId:crypto.randomUUID(),type:'launch',occurredAt:new Date().toISOString()};
const env={DB:db,INSTALL_SALT:'test-only-salt',ADMIN_TOKEN:'test-only-admin'};
const request=b=>new Request('https://metrics.example/event',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});
assert.equal((await worker.fetch(request(body),env)).status,200);
assert.equal((await worker.fetch(request(body),env)).status,200);
for(let i=0;i<2;i++)await worker.fetch(request({...body,eventId:crypto.randomUUID(),type:'use'}),env);
const stats=await worker.fetch(new Request('https://metrics.example/stats',{headers:{Authorization:'Bearer test-only-admin'}}),env).then(r=>r.json());
assert.equal(stats.totalInstalls,1);assert.equal(stats.days[0].activeInstalls,1);assert.equal(stats.days[0].usedInstalls,1);assert.equal(stats.days[0].launches,1);assert.equal(stats.days[0].uses,2);
assert.equal((await worker.fetch(new Request('https://metrics.example/stats'),env)).status,401);
assert.throws(()=>validateEvent({...body,paperTitle:'must not collect'}));assert.throws(()=>validateEvent({...body,type:'keystroke'}));
assert.throws(()=>validateEvent({...body,occurredAt:new Date(0).toISOString()}));
assert.notEqual(await installHash(body.installId,'test-only-salt'),body.installId);
const raw=JSON.stringify(sqlite.prepare('SELECT * FROM installations').all());assert.ok(!raw.includes(body.installId));
console.log('Metrics: private stats, installation hashing, per-day deduplication, separate launch/use counters, retries and payload minimization passed.');
sqlite.close();
