import assert from 'node:assert/strict';
import {COUNT_OPTIONS,discoveryCount,planningMessages,normalizePlan,matchesDiscovery,cleanDoi,rankDiscovery,mergeDiscovery,topicMatch} from './discovery-contract.js';
assert.equal(cleanDoi('https://doi.org/10.3758/s13415-020-00796-3).'),'10.3758/s13415-020-00796-3');
assert.equal(cleanDoi('10.1016/S0005-7916(10)00017-0'),'10.1016/s0005-7916(10)00017-0');
assert.equal(cleanDoi('10.1234/(example))'),'10.1234/(example)');
assert.deepEqual(COUNT_OPTIONS,[5,10,20,50,100]);
assert.equal(discoveryCount(),20);for(const n of [5,10,20,50,100])assert.equal(discoveryCount(String(n)),n);
for(const v of [0,1,4,101,200,1001,5.5,'oops'])assert.throws(()=>discoveryCount(v));
assert.match(planningMessages('test',{},'en')[0].content,/application performs live database retrieval/);
assert.match(planningMessages('中文主题',{language:'any'},'zh')[0].content,/precise ENGLISH search terms/);
const keywords=['frog morphology behavior','青蛙 构造 行为','frog anatomy behavior','蛙类 解剖 行为'];
assert.deepEqual(normalizePlan({queries:keywords,subject_terms:{en:['frog'],zh:['青蛙']},summary:'strategy'},'q').queries,['q',...keywords]);
assert.throws(()=>normalizePlan({queries:['frog morphology']},'q'),/two Chinese/);
assert.throws(()=>normalizePlan({queries:['中文主题','中文行为','中文结构']},'q'),/two English/);
assert.match(planningMessages('frog',{},'en')[0].content,/central research subject AND/);
const same={doi:'10.1234/a',title:'Frog anatomy',recordId:'oa',citations:9,citationSource:'OpenAlex',isOpenAccess:true,searchMatches:[{source:'OpenAlex',query:'frog',rank:2}]};
const both=mergeDiscovery([same,{...same,recordId:'institution',citations:12,citationSource:'Crossref',institutionRecordUrl:'https://library.example/a',searchMatches:[{source:'Library',query:'青蛙',rank:1}]}]);
assert.equal(both.length,1);assert.equal(both[0].recordId,'oa');assert.equal(both[0].citations,9);assert.equal(both[0].citationSource,'OpenAlex');assert.equal(both[0].searchMatches.length,2);assert.ok(both[0].institutionRecordUrl);
assert.equal(mergeDiscovery([same,{...same,doi:'10.1234/b'}]).length,2);
assert.equal(rankDiscovery([{title:'old',year:2001,exactTitleMatch:true},{title:'new',year:2025}],{sort:'newest'})[0].title,'new');
assert.equal(rankDiscovery([{title:'other',searchMatches:[{source:'one',query:'frog',rank:1}]},both[0]],{sort:'combined'})[0].title,same.title);
assert.equal(rankDiscovery([{title:'other'},{title:'Exact title'}],{sort:'combined'},'Exact title')[0].title,'Exact title');
const p={recordId:'real',title:'Source title',authors:['A','B'],year:2021,language:'en',articleType:'research',sourceUrl:'https://example.org/p',isOpenAccess:true,citations:null};
const f={yearStart:2020,yearEnd:2026,language:'en',articleType:'any',source:'open'};
assert.ok(matchesDiscovery(p,f));assert.ok(!matchesDiscovery({...p,language:'unknown'},f));assert.ok(!matchesDiscovery({...p,title:'中文',language:'en'},f));assert.ok(!matchesDiscovery({...p,isOpenAccess:false},f));
console.log('Discovery pipeline contract: counts, strict language/access filtering, model-independent planning, immutable metadata passed.');

assert.equal(topicMatch({title:'Frogs and hopping'},['frog','青蛙']),2);
assert.equal(topicMatch({title:'Robot locomotion',abstract:'Inspired by frogs.'},['frog']),1);
assert.equal(topicMatch({title:'A review of robotics'},['frog','青蛙']),0);
assert.equal(rankDiscovery([{title:'Robots',searchMatches:[{source:'s',query:'a',rank:1}]},{title:'Frog anatomy'}],{},'', ['frog'])[0].title,'Frog anatomy');
