import assert from 'node:assert/strict';
import { researchModePolicy, researchThinkingOptions, normalizeResearchMode } from './research-mode.js';
import { researchTokenBudget } from './ai-response.js';
const config = { model: 'deepseek-v4-pro', provider: 'deepseek' };
assert.equal(normalizeResearchMode('bad'), 'quick');
assert.equal(researchModePolicy('quick').evidenceBudget, 28000);
assert.deepEqual(researchThinkingOptions({model:'deepseek-flash',provider:'deepseek'},'openai-chat','quick'),{thinking:{type:'disabled'}});
assert.equal(researchModePolicy('expert').evidenceBudget, 42000);
assert.equal(researchModePolicy('quick').priority, 'speed');
assert.equal(researchModePolicy('expert').priority, 'depth');
assert.match(researchModePolicy('quick').instruction, /provider-independent/);
assert.match(researchModePolicy('expert').instruction, /not a model identity/);
assert.deepEqual(researchThinkingOptions(config, 'openai-chat', 'quick'), { thinking: { type: 'disabled' } });
assert.deepEqual(researchThinkingOptions(config, 'openai-chat', 'expert'), { thinking: { type: 'enabled' }, reasoning_effort: 'high' });
assert.deepEqual(researchThinkingOptions(config, 'openai-responses', 'quick'), { reasoning: { effort: 'none' } });
assert.deepEqual(researchThinkingOptions(config, 'anthropic-messages', 'expert'), { thinking: { type: 'enabled' }, output_config: { effort: 'high' } });
assert.deepEqual(researchThinkingOptions({ model: 'deepseek-reasoner' }, 'openai-chat', 'quick'), {});
assert.deepEqual(researchThinkingOptions({ model: 'custom-model' }, 'openai-chat', 'expert'), {});
assert.equal(researchTokenBudget(config, 'quick'), 8192);
assert.equal(researchTokenBudget(config, 'expert'), 32768);
assert.equal(researchTokenBudget({ model: 'deepseek-reasoner' }, 'quick'), 16384);
console.log('Research modes: depth guidance, evidence budgets, DeepSeek protocol controls, legacy/generic safety passed.');
