import assert from 'node:assert/strict';
import { ResearchRequest, formatResearchDuration } from './research-request.js';
let clock = 0, calls = [], updates = [];
const run = new ResearchRequest(signal => new Promise(resolve => calls.push({ signal, resolve })), (state, kind) => updates.push([state.status, kind]), () => clock);
const first = run.start();
assert.equal(run.status, 'pending');
await run.start();
assert.equal(calls.length, 1, 'duplicate sends must be ignored');
clock = 62000;
run.pause();
assert.equal(run.status, 'paused');
assert.ok(calls[0].signal.aborted);
assert.equal(formatResearchDuration(run.elapsed()), '1 分 2 秒');
clock = 90000;
assert.equal(run.elapsed(), 62000, 'paused time is excluded');
const second = run.start();
assert.equal(calls.length, 2);
calls[0].resolve('stale answer');
await first;
assert.equal(run.status, 'pending', 'late answer must not override resumed request');
clock = 93000;
calls[1].resolve('final answer');
await second;
assert.equal(run.status, 'done');
assert.equal(run.result, 'final answer');
assert.equal(run.elapsed(), 65000);
assert.equal(formatResearchDuration(59999), '59 秒');
assert.equal(formatResearchDuration(60000), '1 分 0 秒');
assert.equal(formatResearchDuration(62000, 'en'), '1m 2s');
const failed = new ResearchRequest(async () => { throw new Error('network'); }, () => {});
await failed.start();
assert.equal(failed.status, 'error');
assert.equal(failed.error.message, 'network');
console.log('Research lifecycle: pause, abort, resume, duplicates, stale response, cumulative timer and failure passed.');
