const knownMessages = {
  '外部 Agent 已离线，请在模型接入中重新连接；手动 MCP 接入需要恢复任务循环。': 'The external agent is offline. Reconnect in Model connection; manual MCP requires its task loop to resume.',
  '外部 Agent 已离线，请连接桌面端按需调用，或恢复手动 MCP 任务循环。': 'The external agent is offline. Enable desktop on-demand execution or resume the manual MCP task loop.',
  'PDF 的文字编码异常，提取结果不可靠。原文已保留，请先 OCR 或补充可读的 PDF / MD 后继续。': 'This PDF has unreliable text encoding. The original is retained. Run OCR or add a readable PDF / Markdown file, then continue.',
  '原文尚未保存到磁盘，请检查可用空间。': 'The original has not been saved to disk. Check available storage.',
  '原文已保存；请连接模型后继续分析。': 'Original saved. Connect a model to continue analysis.',
  '尚无可分析的 MD 原文。': 'No Markdown original is available for analysis.',
  '请先为这篇论文补充原文文件。': 'Add this paper’s original file first.',
  '本地原文文件不可用，请补充原文。': 'Local original unavailable. Add the original file.',
  'MD 未保存到磁盘，请检查可用空间后继续。': 'Markdown was not saved to disk. Check storage and continue.',
  '论文节点已删除。': 'Paper node was deleted.',
  '暂未找到精确匹配的学术记录，被引量保持未知。': 'No exact scholarly record found; citation count remains unknown.',
  '单个文档请小于 40 MB。': 'Each document must be under 40 MB.',
  'PDF 没有足够的可提取文字，可能是扫描件。请先 OCR，再上传 PDF 或 MD。': 'This PDF has insufficient extractable text and may be scanned. Run OCR first, then upload the PDF or Markdown.',
  '研究材料支持 PDF、MD、TXT、CSV、JSON、TeX。请先将其他格式转换为 PDF 或 MD。': 'Research materials support PDF, MD, TXT, CSV, JSON and TeX. Convert other formats to PDF or Markdown first.',
  '文件没有可读取的文字。': 'The file contains no readable text.',
  '图片支持 PNG、JPEG、WebP。': 'Supported images: PNG, JPEG and WebP.',
  '单张图片请小于 5 MB。': 'Each image must be under 5 MB.',
  '模型引用了不存在的证据编号，请重试。': 'The model referenced an unknown evidence ID. Please retry.',
  '本地服务不可用，请使用 LitGraph 本地启动器打开。': 'Local service unavailable. Open LitGraph using its local launcher.',
  '本地服务请求失败': 'Local service request failed',
  '外部 Agent 已离线，请让它恢复任务循环后重试。': 'The external agent is offline. Restart its task loop and retry.',
  '外部 Agent 超过 15 分钟未返回，请检查它的任务状态。': 'The external agent has not responded for 15 minutes. Check its task status.',
  '未提供可下载的 PDF 地址，请手动添加原文。': 'No downloadable PDF URL was provided. Add the full text manually.',
  'PDF 超过 40 MB': 'PDF exceeds 40 MB', '项目已切换': 'The project has changed'
};
const codeMessages = {
  output_limit: 'The model reached its output limit before completing an answer. Reduce the paper scope or simplify the question and retry. This is not a protocol mismatch.',
  refusal: 'The model did not answer this question. Rephrase it and retry.',
  incomplete: 'The model request did not complete. Retry or check the provider status.',
  reasoning_only: 'The model returned reasoning but no final answer. Try “Retry in quick mode”. If that also fails, check whether your provider supports disabling reasoning or choose another model. Reasoning has not been substituted for an answer.',
  tool_calls: 'The model requested a tool that is not connected to this research chat. No final answer was received.',
  empty_answer: 'No final answer was returned. Check the selected API protocol or retry later.',
  invalid_json: 'The endpoint did not return valid JSON. Check the API or proxy URL; do not use an ordinary chat website URL.'
};
const sourceMessages = {
  'Institution page blocked; skipped this paper. Saved files are retained.': '机构页面已封锁，已跳过当前论文；已保存文件保留。',
  'Institution verification timed out; skipped this paper. Saved files are retained.': '机构人工验证等待超时，已跳过当前论文；已保存文件保留。',
  'Institution search requires the desktop application’s authenticated browser session. Open the installed application to search this source.': '机构检索需要桌面端内置浏览器的登录会话，请在已安装的 LitGraph 中检索此来源。',
  'The institution browser did not return readable search records. Open the institution window and check the current results page.': '机构浏览器未返回可读取的检索记录，请打开机构窗口检查当前结果页面。',
  'Institution source records are retained; unavailable supplementary metadata and citation counts remain unknown.': '已保留机构页面中的真实记录；暂未获取的补充元数据及被引量保持未知。',
  'Supplementary metadata for a different paper was ignored; the institution source record and its access route were preserved.': '已忽略与当前论文不符的补充元数据，保留机构来源记录及其访问路径。',
  'Some source records lack a year, language or article type needed to verify the selected filters. Open the source record or broaden the filters.': '部分来源记录缺少年份、语言或文献类型，无法核实是否符合当前筛选条件。请查看来源记录，或放宽筛选条件。',
  'Some institution results were outside the selected year, language or article-type filters.': '部分机构检索结果不符合当前选择的年份、语言或文献类型，已从结果中筛除。',
  'Matching institution records already exist in the current project and were excluded from new results.': '匹配的机构记录已存在于当前项目中，因此未作为新论文重复显示。',
  'The institution page contained unreadable result records. Open the institution window to check the current page.': '机构页面包含暂时无法读取的结果记录，请打开机构窗口检查当前页面。',
  'Institution pagination stopped before all pages were read; records already found are retained.': '机构检索分页未能全部读取，已保留当前找到的真实记录。',
  'Codex executable not found. Install the official native CLI, sign in once, then reconnect. You can also choose its executable.': '未找到 Codex 程序。请安装官方原生 CLI 并登录一次，再重新连接；也可以手动选择其程序文件。',
  'Claude Code executable not found. Install the official native CLI, sign in once, then reconnect. You can also choose its executable.': '未找到 Claude Code 程序。请安装官方原生 CLI 并登录一次，再重新连接；也可以手动选择其程序文件。',
  'Agent returned an invalid response. Update the official CLI and reconnect.': '外部 Agent 返回格式不正确，请更新官方 CLI 后重新连接。',
  'Claude Code could not complete the task. Check its login, quota and model access.': 'Claude Code 未能完成任务，请检查该工具的登录状态、额度和模型权限。',
  'Codex could not complete the task. Check its login, quota and model access.': 'Codex 未能完成任务，请检查该工具的登录状态、额度和模型权限。',
  'Agent did not return a final answer.': '外部 Agent 没有返回最终回答，请重试或缩小论文范围。',
  'Agent did not complete the task.': '外部 Agent 的任务尚未完整完成，未将部分回答当作最终结果。',
  'Agent execution failed. Check CLI login, quota and version; reconnect to test access.': '外部 Agent 调用失败，请检查 CLI 的登录状态、额度和版本，然后重新连接验证。',
  'Unable to start the agent executable. Reconnect and check the CLI installation.': '无法启动外部 Agent，请检查 CLI 安装位置并重新连接。',
  'Agent timed out. Try a smaller paper scope.': '外部 Agent 响应超时，请检查网络或缩小论文范围后重试。',
  'Agent response exceeds 4 MB.': '外部 Agent 返回内容超过 4 MB，请缩小任务范围。',
  'Agent input exceeds 4 MB. Select fewer papers.': '提交的原文材料超过 4 MB，请减少选择的论文数量。',
  'This agent connection accepts text only.': '此 Agent 接入方式目前仅支持文本，不支持图片输入。',
  'Finish or cancel current agent tasks before changing the connection.': '请先完成或暂停现有 Agent 任务，再更改接入方式。',
  'Choose the official agent executable.': '请选择对应工具的官方原生可执行程序。',
  'Agent connection test did not return the expected answer.': '接入验证未返回预期结果，尚未保存该连接。',
  'Connect the external agent first.': '请先连接外部 Agent。',
  'Agent queue is full. Wait or cancel a task.': 'Agent 任务队列已满，请等待或取消现有任务。',
  'Wait for the connection test to finish.': '请等待接入验证结束。',
  'This gateway has no verified WebVPN routing configuration. Use the institution or publisher sign-in window.': '该入口尚无已核验的 WebVPN 路由配置，请使用机构或出版方的登录窗口。',
  'The source returned an incomplete PDF.': '来源返回的 PDF 不完整，未保存为可用原文。请补充完整文件。',
  'The source returned a page instead of a PDF. Authentication or a manual download may be required.': '来源返回的是网页而不是 PDF，可能需要机构认证或手动补充原文。',
  'The verified open-access record did not provide an accessible PDF. Supply the original or use an authenticated institution session.': '已核验的开放获取记录未提供当前可下载的 PDF。请补充原文，或使用已登录的机构会话。',
  'No verified open-access original is available. Use your institution or supply an original you are permitted to access.': '尚无已核验的开放原文。请通过机构获取，或补充你有权使用的原文。',
  'Institution authentication is available in the desktop application, not this browser preview. Open-access acquisition was attempted; supply the original or use the installed application.': '浏览器预览不具备桌面端的机构登录会话。已检查开放来源，请补充原文或在安装版中使用机构访问。',
  'No accessible original was obtained. Sign in through the institution window or supply the original.': '未获取到可用原文。请在机构窗口完成登录，或手动补充原文。',
  'This paper is already being acquired.': '这篇论文正在获取中，请等待当前处理结束。',
  'Two downloads are already running. Wait for a slot.': '已有两篇论文正在获取，等待空闲后可继续。',
  'Source HTTP 429: the source rate limit was reached. Try again later.': '来源请求达到频率限制（429），请稍后继续。',
  'Source HTTP 403: this site denied automated access. Use an available repository or add the original manually.': '来源网站拒绝自动获取（403）。请使用可用的开放仓储，或手动补充原文。',
  'Source HTTP 404: this full-text link is missing or has moved.': '全文链接不存在或已移动（404）。请从来源页面重新获取原文。',
  'Source HTTP 410: this full-text link is missing or has moved.': '全文链接已失效（410）。请从来源页面重新获取原文。',
  'Source timed out before a complete response was received. Saved work is retained.': '来源响应超时，已完成的内容已保留，可以稍后继续。',
  'This record is open to read, but no downloadable PDF was provided by its verified sources. Open the source and add the original file manually.': '该记录标记为开放阅读，但已核验的来源未提供可下载的 PDF。请打开来源页面并手动补充原文。',
  'No verified open-access original is available. Use your institution or add an original file you are permitted to access.': '尚无已核验的开放原文。请通过机构获取，或手动补充你有权使用的原文文件。',
  'No automatically accessible open PDF. Use the source or institution portal, then add the original file.': '未找到可自动获取的开放 PDF。请通过来源或机构入口获取后手动补充原文。',
  'AI did not return a complete paper analysis.': '模型未返回完整的论文分析，请继续重试。',
  'AI did not return a complete paper classification.': '模型未返回完整的论文分类，请继续重试。',
  'AI returned a relationship without matching original evidence.': '旧分析中的连线证据未匹配原文。请点击继续，新版将保留总结并单独校验连线。',
  'Source HTTP 403': '来源拒绝访问（403），可能需要登录或不允许自动下载。',
  'Source HTTP 404': '来源链接不存在或已失效（404）。',
  'Institution HTTP 401': '机构认证未完成或已失效，请在机构窗口重新登录。',
  'Institution HTTP 403': '机构或出版方拒绝访问（403），请确认订阅权限，并在机构窗口打开原文。',
  'Institution HTTP 404': '机构原文链接不存在或已移动（404），请从机构论文页面重新打开。',
  'Institution response was interrupted.': '机构响应中断，已保存内容保留。',
  'This operation was aborted': '请求中断或超时，已保存内容保留。',
  'The operation was aborted': '请求中断或超时，已保存内容保留。'
};
export function localizedError(error, language = 'zh') {
  const message = (typeof error === 'string' ? error : error?.message || (language === 'en' ? 'Unknown error' : '未知错误')).replace(/^Error invoking remote method 'desktop:(?:institution|agent-runtime)': (?:Error: )?/, '');
  if (language !== 'en') return sourceMessages[message] || message.split('; ').map(part=>sourceMessages[part] || part).join('；');
  // Translate only our own messages/codes, never model answers or arbitrary provider text.
  return codeMessages[error?.code] || knownMessages[message] || message;
}
